### ISSUE TITLE
Consider giving an order to the categories in the sidebar

### ISSUE THREAD

**Issue by seanhagen** [flyingoctopus/youngagrarians#17]
What order?

**Comment by seanhagen** [comment]
If you add an order field, can you add the filter flag from #28 at the same time?

**Comment by flyingoctopus** [comment]
exactly. any. sortable.

_"Gort, Klaatu barada nikto"_

```
    778 968 6296

 flyingoctopus.net
```

   vincent.vanhaaff.com

**Comment by seanhagen** [comment]
Leave for later.
