### ISSUE TITLE
single page app

### ISSUE THREAD

**Issue by flyingoctopus** [flyingoctopus/youngagrarians#2]
backboneify!

**Comment by seanhagen** [comment]
Working on this. The latest commit to my repo ( which I'll merge shortly to your branch shortly ) now has the following:
- map is rendered on page-view, shows a map centered on BC, with all of BC viewable
- map is set to "road map" type ( non-satellite )
- categories populate the sidebar
- clicking categories filters the markers present on the map

Coming up soon:
- clicking categories also filters results list
- moving & zooming in/out on map changes results list

**Comment by seanhagen** [comment]
So far, the 'click category to filter list' works, and so does the zooming. Just need to get the two routes ( an index route, and a 'view location' route for deep linking ) setup and working. Should be pretty simple to get the routes working.

I think it'll mostly just be moving some of the code into the already created router ( thanks backbone-rails! ), I just need to rip out some of the pre-defined routes, and only have the two we need.

Question: should 'add a location' be a route, or should it just be a view event?

**Comment by flyingoctopus** [comment]
I dont think that adding a location needs to be deep linkable, it could
just be a modal showing the form that we will PUT to a rails route that is
already in there iirc. Glad to see this on there!

_"Gort, Klaatu barada nikto"_

```
    778 968 6296

 flyingoctopus.net
```

   vincent.vanhaaff.com
