### ISSUE TITLE
Fix pin interaction issues.

### ISSUE THREAD

**Issue by seanhagen** [flyingoctopus/youngagrarians#23]
What are they?

**Comment by seanhagen** [comment]
You probably have a better idea of what this one is about.

**Comment by flyingoctopus** [comment]
Some pins are un-clickable (their corresponding bubble dialog wont show
up). It's possible that occurs when two pins overlap. Quick google showed
[this](http://stackoverflow.com/questions/10078339/google-maps-cluster-display-bubble-on-marker-click).

_"Gort, Klaatu barada nikto"_

```
    778 968 6296

 flyingoctopus.net
```

   vincent.vanhaaff.com
