### ISSUE TITLE
Removed non-web resources from sidebar, now not showing up in results list

### ISSUE THREAD

**Issue by seanhagen** [flyingoctopus/youngagrarians#28]
Urgh. Maybe we can add a field to the categories table ( just a flag ), and use that to determine whether or not the result item is affected by any of the filtering.

**Comment by flyingoctopus** [comment]
i was just going to set the logic on the client-side to ignore rendering
the buttons if yadda yadda. the flag thing is probably the Right Way, but I
want to stop the data finagling for this phase. Let me know your thoughts.

_"Gort, Klaatu barada nikto"_

```
    778 968 6296

 flyingoctopus.net
```

   vincent.vanhaaff.com

**Comment by seanhagen** [comment]
Fixed it by hard-coding in the fix. Pushed in commit 7a683c906113535304d760140dfd6fd3e75df908 to master.
